// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSlSYSeoa9fA43KGdCPov3LtAMeXQZ0BY',
    appId: '1:1082842985559:android:635e4aa0c772451d471f12',
    messagingSenderId: '1082842985559',
    projectId: 'hideyuki-firebase',
    storageBucket: 'hideyuki-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-N8lZNZRZl5PCVMAhxTkA_edocgPYm7Q',
    appId: '1:1082842985559:ios:770a5f0e5ab92c4f471f12',
    messagingSenderId: '1082842985559',
    projectId: 'hideyuki-firebase',
    storageBucket: 'hideyuki-firebase.appspot.com',
    androidClientId: '1082842985559-a0lh8n0fi1ohs49v0n991jg5ui6flo2v.apps.googleusercontent.com',
    iosClientId: '1082842985559-c8bmdju4974qtqr0hm9kei9dpp505pjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.testDebstechRiverpod2TodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-N8lZNZRZl5PCVMAhxTkA_edocgPYm7Q',
    appId: '1:1082842985559:ios:2e687ec58fafdf30471f12',
    messagingSenderId: '1082842985559',
    projectId: 'hideyuki-firebase',
    storageBucket: 'hideyuki-firebase.appspot.com',
    androidClientId: '1082842985559-a0lh8n0fi1ohs49v0n991jg5ui6flo2v.apps.googleusercontent.com',
    iosClientId: '1082842985559-k45ot78vraa2bjsbthcq5gq5lo7uqirn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testDebstechRiverpod2TodoApp.RunnerTests',
  );
}
